const products = [
    {
        '_id': '1',
        'name': 'Oraimo Freepods',
        'image': './images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '3',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
]

export default products;